import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Ozodbek/Navbar";
import Footer from "@/components/Ozodbek/Footer";
const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin", "cyrillic"],
    weight: ["300", "400", "500", "700", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html className="h-full" lang="en">
            <body
                className={`${nunito.variable} font-nunito antialiased h-full flex flex-col`}
            >
                <Navbar />
                <main className="grow">{children}</main>

                <Footer />
            </body>
        </html>
    );
}
